# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 676)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font: 75 10pt \"Consolas\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.LogText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LogText.setGeometry(QtCore.QRect(40, 140, 711, 441))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.LogText.setFont(font)
        self.LogText.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"")
        self.LogText.setPlainText("")
        self.LogText.setObjectName("LogText")
        self.text1 = QtWidgets.QLabel(self.centralwidget)
        self.text1.setGeometry(QtCore.QRect(40, 100, 121, 31))
        self.text1.setObjectName("text1")
        self.InputText = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.InputText.setGeometry(QtCore.QRect(40, 60, 711, 31))
        self.InputText.setObjectName("InputText")
        self.text2 = QtWidgets.QLabel(self.centralwidget)
        self.text2.setGeometry(QtCore.QRect(40, 20, 141, 31))
        self.text2.setObjectName("text2")
        self.text2_2 = QtWidgets.QLabel(self.centralwidget)
        self.text2_2.setGeometry(QtCore.QRect(810, 20, 141, 31))
        self.text2_2.setObjectName("text2_2")
        self.FuncomboBox = QtWidgets.QComboBox(self.centralwidget)
        self.FuncomboBox.setGeometry(QtCore.QRect(810, 60, 251, 31))
        self.FuncomboBox.setObjectName("FuncomboBox")
        self.FuncomboBox.addItem("")
        self.FuncomboBox.addItem("")
        self.LikeButton = QtWidgets.QPushButton(self.centralwidget)
        self.LikeButton.setGeometry(QtCore.QRect(980, 300, 141, 71))
        self.LikeButton.setStyleSheet("\n"
"background-color: rgb(0, 170, 255);")
        self.LikeButton.setObjectName("LikeButton")
        self.OpenButton = QtWidgets.QPushButton(self.centralwidget)
        self.OpenButton.setGeometry(QtCore.QRect(810, 300, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.OpenButton.setFont(font)
        self.OpenButton.setStyleSheet("background-color:rgb(208, 255, 176)")
        self.OpenButton.setObjectName("OpenButton")
        self.ProcessButton = QtWidgets.QPushButton(self.centralwidget)
        self.ProcessButton.setGeometry(QtCore.QRect(810, 160, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        font.setKerning(True)
        self.ProcessButton.setFont(font)
        self.ProcessButton.setStyleSheet("background-color:rgb(255, 208, 218);")
        self.ProcessButton.setAutoDefault(False)
        self.ProcessButton.setObjectName("ProcessButton")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(810, 430, 311, 151))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.DonateButton = QtWidgets.QPushButton(self.centralwidget)
        self.DonateButton.setGeometry(QtCore.QRect(980, 160, 141, 71))
        self.DonateButton.setStyleSheet("\n"
"background-color: rgb(85, 170, 127);")
        self.DonateButton.setObjectName("DonateButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1168, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.menuFile.addAction(self.actionOpen)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "houkingyu♥can"))
        self.text1.setText(_translate("MainWindow", "日志："))
        self.text2.setText(_translate("MainWindow", "需处理excel表格："))
        self.text2_2.setText(_translate("MainWindow", "功能："))
        self.FuncomboBox.setItemText(0, _translate("MainWindow", "选择"))
        self.FuncomboBox.setItemText(1, _translate("MainWindow", "三费-智慧城市"))
        self.LikeButton.setText(_translate("MainWindow", "点个赞吧"))
        self.OpenButton.setText(_translate("MainWindow", "打开结果文件"))
        self.ProcessButton.setText(_translate("MainWindow", "开始处理"))
        self.textBrowser_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">使用说明：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">（1）选择一个excel文件</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">（2）选择一个功能</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">（3）点击“开始处理”</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">©2022 CopyRight Houking Yu</p></body></html>"))
        self.DonateButton.setText(_translate("MainWindow", "打赏"))
        self.menuFile.setTitle(_translate("MainWindow", "文件"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
